### ISSUE TITLE
Gerador de simulados ENEM

### ISSUE THREAD

**Issue by xValentim** [xValentim/edu-bot#20]

**Comment by xValentim** [comment]
@marlonsp @HudsonArauj @talesitf @SamuelJabes @EnzoSilva14 

Esse aqui também está meio em aberto (como o de sistema de recomendações). Mas podem começar a pensar como fazer um gerador de simulados. 

Sugestão:
- Peguem provas antigas e apliquem alguma rubrica + RAG pra gerar questões similares.
- Foquem em assuntos que são mais textuais, como história, geografia.... 

Dica:
- Feito é melhor que perfeito. Tenham visão de MVP, não precisa estar 100% redondo. Tenham a ideia consistente e não pilhem com imperfeições iniciais.

**Comment by HudsonArauj** [comment]
Como foi conversado @marlonsp  e @EnzoSilva14 testem primeiro para humanas. Como o pinecone ja ta sendo usado, provavelmente um double RAG é bem vindo nesse momento, usem o mongo pra isso.
