### ISSUE TITLE
Implementar alguma técnica avançada de RAG

### ISSUE THREAD

**Issue by xValentim** [xValentim/edu-bot#5]

**Comment by xValentim** [comment]
@SamuelJabes Conduza os meninos nessa tarefa por favor.

**Comment by HudsonArauj** [comment]
@marlonsp  e @EnzoSilva14 , aqui o @SamuelJabes irá mostrar para vcs alguma técnica de RAG avançada, caso já tenham dominado o RAG simples. Não deixe de chamar ele no privado em qualquer hora do dia.
