### ISSUE TITLE
Criar ambiente de dev no Railway

### ISSUE THREAD

**Issue by xValentim** [xValentim/edu-bot#6]

**Comment by xValentim** [comment]
Crie um ambiente de Dev que está sincronizado com uma branch dev. @HudsonArauj @SamuelJabes 

Adicione por favor o marlon e o enzo nesse projeto e conduza eles pra aprender a usar o Github com os padrões que a gente costuma usar.

**Comment by HudsonArauj** [comment]
Olá @marlonsp, bem vindo ao repo do edu, alguns issues serão atribuída a vc, fique atento.

**Comment by HudsonArauj** [comment]
Olá @EnzoSilva14 , bem vindo ao repo do edu, algumas issues serão atribuída a vc, fique atento.
