### ISSUE TITLE
Criar prompt com markdown

### ISSUE THREAD

**Issue by xValentim** [xValentim/edu-bot#7]

**Comment by HudsonArauj** [comment]
senhores @marlonsp e @EnzoSilva14 criem um prompt com markdown, lembre - se do padrão de commits que geralmente é usado por nós devs.
dica : https://blog.geekhunter.com.br/o-que-e-commit-e-como-usar-commits-semanticos/

**Comment by HudsonArauj** [comment]
Para vcs o ambiente dev é o ambiente de produção, ao realizar o PR(pull request) mandem para lá suas atualizações. Não esqueçam de criar branchs para tasks específicas, assim evitam conflitos no merge.
obs: Jamais derrube ambiente de prod. Caso aconteça, ligue para o dev responsável do projeto(@SamuelJabes)
