### ISSUE TITLE
Criar tela de login

### ISSUE THREAD

**Issue by xValentim** [xValentim/edu-bot#9]

**Comment by HudsonArauj** [comment]
@marlonsp  e @EnzoSilva14 façam uma tela de login no streamlit para o eduBot. Para informações:
https://docs.streamlit.io/

**Comment by HudsonArauj** [comment]
@EnzoSilva14  e @marlonsp, boas soluções, um mix das duas será utilizado em dev.

**Comment by HudsonArauj** [comment]
@marlonsp e  @EnzoSilva14 testem em dev e vejam se tem algum bug.
https://edu-bot-dev.up.railway.app/

Descubram a senha e user a partir do IP...
